### ISSUE TITLE
D3FEND Does Not Currently Address ZTA Concepts Like JIT/JEA

### ISSUE THREAD

**Issue by OldGoat-Biker** [d3fend/d3fend-ontology#16]
Some of the Automation, Scale, and Time and Behavior orchestration concepts of ZTA aren't currently integrated/addressed in D3FEND. D3FEND focuses on binary (do/don't do) countermeasures vs adaptive levels and speed of response based on aggregated/analyzed info. Adds additional weight to argument for another high-level Tactic, ala Adapt, to be included.

**Comment by netfl0** [comment]
Orchestration (i.e. orchestrated defensive techniques) can be modeled using :Procedure and :Step , this is a very recent addition, it's not on the website but it's in the ontology. 

Regarding aggregated info, we'd need specific examples of what information is being aggregated (analyzed?) in order to describe what is being done.

We have the build the model from the bottom up based on digital artifacts or we'll be introducing subjectivity.

**Comment by netfl0** [comment]
Another thought I had was the distinction between functional and non-functional requirements. We are focused on functional requirements, I believe there are some implied in the question, we just need to pull them out. Closing ticket, we can create another when we have a concrete function we want to add.
